/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "var(--primary)",
          50:  "var(--primary-50)",
          100: "#B3EBEA",
          200: "#80DEDC",
          300: "#4DCFCD",
          400: "#26C6C4",
          500: "var(--primary)",
          600: "#008C8A",
          700: "var(--primary-700)",
          800: "#004E4D",
          900: "#002F2E",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          50: "#E3F4FC",
          100: "#BFE2F8",
          200: "#8ACBF3",
          300: "#54B3EE",
          400: "#2AADE8",
          500: "var(--secondary)",
          600: "#1380BB",
          700: "#0D5F8B",
          800: "#073E5C",
          900: "#031F30",
        },
        success:  { DEFAULT: "var(--success)", light: "#60A960", dark: "#1A591A" },
        warning:  { DEFAULT: "var(--warning)", light: "#FAAA24", dark: "#B87000" },
        danger:   { DEFAULT: "var(--danger)",  light: "#FF3322", dark: "#A51000" },
        magenta:  { DEFAULT: "#D80073", light: "#FF3399", dark: "#A30058" },
        purple:   { DEFAULT: "#A200FF", light: "#C155FF", dark: "#7A00BF" },
        surface: {
          DEFAULT: "var(--surface)",
          raised: "var(--surface-raised)",
          overlay: "var(--surface-overlay)",
          border: "var(--surface-border)",
          inverse: "var(--surface-inverse)",
        },
        bg: {
          DEFAULT: "var(--bg)",
          secondary: "var(--bg-secondary)",
          inverse: "var(--bg-inverse)",
        },
        txt: {
          primary:   "var(--txt-primary)",
          secondary: "var(--txt-secondary)",
          muted:     "var(--txt-muted)",
          inverse:   "var(--txt-inverse)",
        },
      },
      fontFamily: {
        sans:  ["Inter_400Regular", "Segoe UI", "System"],
        mid:   ["Inter_500Medium",  "Segoe UI", "System"],
        semi:  ["Inter_600SemiBold","Segoe UI", "System"],
        bold:  ["Inter_700Bold",    "Segoe UI", "System"],
        black: ["Inter_900Black",   "Segoe UI", "System"],
        light: ["Inter_300Light",   "Segoe UI", "System"],
      },
      borderRadius: {
        none: "0px",
        xs: "0px",
        sm: "0px",
        DEFAULT: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        "3xl": "0px",
        "4xl": "0px",
        full: "0px",
      },
      spacing: {
        "4.5": "18px",
        "13":  "52px",
        "15":  "60px",
        "18":  "72px",
        "22":  "88px",
        "88":  "352px",
      },
    },
  },
  plugins: [],
};